version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://db:27017/ecommerce
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - db-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
