Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Provision with Ansible
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = "v"
  end
end

